### ISSUE TITLE
about the input

### ISSUE THREAD

**Issue by 212646490** [zhangweiqwe/fugueMini#1]
Hello,how to set the input and what is the input format?thanks~

**Comment by zhangweiqwe** [comment]
你说汉语就好了，问题描述不清楚

**Comment by 212646490** [comment]
恩恩，谢谢。我是想问一下输入的格式（这是我的输入格式：http://user:pwd@ip:post）以及给用户名/密码以及ip和端口号加密是在哪实现的？
