### ISSUE TITLE
关于输入/加密

### ISSUE THREAD

**Issue by 212646490** [zhangweiqwe/fugueMini#2]
恩恩，谢谢。我是想问一下输入的格式（这是我的输入格式：http://user:pwd@ip:post）以及给用户名/密码以及ip和端口号加密是在哪实现的？

**Comment by zhangweiqwe** [comment]
打不开链接，这个是直接解析的，也没有什么加密，你要加密的话，主要加密请求和响应，需要两套证书，这样每次请求会损耗一定性能
